apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashudb
  name: ashudb
spec:
  externalName: ciscodb.cqypbbo9r82r.us-east-1.rds.amazonaws.com
  ports:
  - name: "3306"
    port: 3306
    protocol: TCP
    targetPort: 3306
  type: ExternalName
status:
  loadBalancer: {}
