apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ashuwebpod
  name: ashuwebpod # name of POD 
spec:
  containers:
  - image: dockerashu/ashuwebapp:v1 # docker image 
    name: ashuwebpod # name of container 
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
